package cli

import (
	"fmt"
	"time"

	"github.com/spf13/cobra"

	"blcli/pkg/bootstrap"
)

// NewApplyTerraformCommand creates the apply terraform subcommand
func NewApplyTerraformCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "terraform",
		Short: "Apply Terraform configurations to GCP",
		Long: `Apply Terraform configurations to GCP.

This command executes terraform apply for all terraform projects in the specified directory.
It runs in the following order:
1. First, executes init directories in numeric order (e.g., 0-codestore, 1-my-org-projects)
2. Then, executes gcp project directories

Examples:
  # Apply all terraform projects
  blcli apply terraform -d ./generated/terraform

  # Apply specific project
  blcli apply terraform -d ./generated/terraform --project my-project

  # Apply with GCS emulator (for testing)
  blcli apply terraform -d ./generated/terraform --use-emulator --auto-approve`,
		Example: `  # Apply all terraform projects
  blcli apply terraform -d ./generated/terraform

  # Apply specific project
  blcli apply terraform -d ./generated/terraform --project my-project

  # Apply with GCS emulator
  blcli apply terraform -d ./generated/terraform --use-emulator --auto-approve`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if applyTerraformDir == "" {
				return fmt.Errorf("terraform directory is required. Use -d to specify the directory")
			}

			// Parse timeout
			timeout := 1 * time.Hour
			if applyTerraformTimeout != "" {
				var err error
				timeout, err = time.ParseDuration(applyTerraformTimeout)
				if err != nil {
					return fmt.Errorf("invalid timeout duration: %w", err)
				}
			}

			// Don't print full usage on runtime errors (e.g. terraform apply failure)
			cmd.SilenceUsage = true

			return bootstrap.ExecuteApplyTerraform(bootstrap.ApplyTerraformOptions{
				TerraformDir:    applyTerraformDir,
				ProjectName:     applyTerraformProject,
				Timeout:         timeout,
				UseEmulator:     applyTerraformUseEmulator,
				EmulatorPort:    applyTerraformEmulatorPort,
				EmulatorDataDir: applyTerraformEmulatorDataDir,
				AutoApprove:     applyTerraformAutoApprove,
				SkipBackend:     applyTerraformSkipBackend,
				TemplateRepo:    applyTerraformTemplateRepo,
				DryRun:          applyTerraformDryRun,
			})
		},
	}

	cmd.Flags().StringVarP(&applyTerraformDir, "dir", "d", "",
		"Terraform directory path (required, generated by 'blcli init terraform')")
	cmd.Flags().StringVarP(&applyTerraformProject, "project", "p", "",
		"Specific terraform project name to apply (if not specified, applies all projects)")
	cmd.Flags().StringVar(&applyTerraformTimeout, "timeout", "1h",
		"Apply timeout duration (e.g., 30m, 1h). Default: 1h")
	cmd.Flags().BoolVar(&applyTerraformUseEmulator, "use-emulator", false,
		"Use GCS emulator instead of real GCS (for testing)")
	cmd.Flags().IntVar(&applyTerraformEmulatorPort, "emulator-port", 4443,
		"GCS emulator port (default: 4443)")
	cmd.Flags().StringVar(&applyTerraformEmulatorDataDir, "emulator-data-dir", "",
		"GCS emulator data directory")
	cmd.Flags().BoolVar(&applyTerraformAutoApprove, "auto-approve", false,
		"Automatically approve terraform apply without confirmation")
	cmd.Flags().BoolVar(&applyTerraformSkipBackend, "skip-backend", false,
		"Skip backend initialization (for testing only)")
	cmd.Flags().StringVarP(&applyTerraformTemplateRepo, "template-repo", "r", "",
		"Template repository URL or local path (optional, used for dependency resolution)")
	cmd.Flags().BoolVar(&applyTerraformDryRun, "dry-run", false,
		"Preview execution plan without applying changes")

	return cmd
}
