package cli

import (
	"fmt"
	"time"

	"github.com/spf13/cobra"

	"blcli/pkg/bootstrap"
)

// NewApplyInitCommand creates the apply init subcommand (step 0: init dirs only, prepare first then init).
func NewApplyInitCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Apply Terraform init directories only (step 0: remote state, then init)",
		Long: `Apply only the Terraform init phase: first run prepare init components (e.g. 0-terraform-statestore for remote state),
then run the rest of init directories. Does not apply gcp project directories.

Use this as step 0 before 'blcli apply terraform' to create the remote state bucket first.
Order is read from .blcli.marker (written by 'blcli init').`,
		Example: `  # Apply init only (prepare + init dirs)
  blcli apply init -d ./workspace/output/terraform

  # With auto-approve
  blcli apply init -d ./workspace/output/terraform --auto-approve`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if applyTerraformDir == "" {
				return fmt.Errorf("terraform directory is required. Use -d to specify the directory")
			}
			timeout := 1 * time.Hour
			if applyTerraformTimeout != "" {
				var err error
				timeout, err = time.ParseDuration(applyTerraformTimeout)
				if err != nil {
					return fmt.Errorf("invalid timeout duration: %w", err)
				}
			}
			initDelay := 30 * time.Second
			if applyTerraformInitDelay != "" {
				var err error
				initDelay, err = time.ParseDuration(applyTerraformInitDelay)
				if err != nil {
					return fmt.Errorf("invalid init-delay duration: %w", err)
				}
			}
			return bootstrap.ExecuteApplyInit(bootstrap.ApplyTerraformOptions{
				TerraformDir:    applyTerraformDir,
				Timeout:         timeout,
				InitDelay:       initDelay,
				UseEmulator:     applyTerraformUseEmulator,
				EmulatorPort:    applyTerraformEmulatorPort,
				EmulatorDataDir: applyTerraformEmulatorDataDir,
				AutoApprove:     applyTerraformAutoApprove,
				SkipBackend:     applyTerraformSkipBackend,
			})
		},
	}
	cmd.Flags().StringVarP(&applyTerraformDir, "dir", "d", "",
		"Terraform directory path (required, generated by 'blcli init -m terraform')")
	cmd.Flags().StringVar(&applyTerraformTimeout, "timeout", "1h",
		"Apply timeout duration (e.g., 30m, 1h). Default: 1h")
	cmd.Flags().StringVar(&applyTerraformInitDelay, "init-delay", "30s",
		"Delay after each init directory to allow GCP propagation (e.g., 30s, 0 to disable). Default: 30s")
	cmd.Flags().BoolVar(&applyTerraformUseEmulator, "use-emulator", false,
		"Use GCS emulator instead of real GCS (for testing)")
	cmd.Flags().IntVar(&applyTerraformEmulatorPort, "emulator-port", 4443,
		"GCS emulator port (default: 4443)")
	cmd.Flags().StringVar(&applyTerraformEmulatorDataDir, "emulator-data-dir", "",
		"GCS emulator data directory")
	cmd.Flags().BoolVar(&applyTerraformAutoApprove, "auto-approve", false,
		"Automatically approve terraform apply without confirmation")
	cmd.Flags().BoolVar(&applyTerraformSkipBackend, "skip-backend", false,
		"Skip backend initialization (for testing only)")
	return cmd
}
