package cli

import (
	"fmt"
	"time"

	"github.com/spf13/cobra"

	"blcli/pkg/bootstrap"
	"blcli/pkg/template"
)

// NewApplyKubernetesCommand creates the apply kubernetes subcommand
func NewApplyKubernetesCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "kubernetes",
		Short: "Deploy Kubernetes resources to cluster",
		Long: `Deploy Kubernetes resources to cluster.

This command applies Kubernetes manifests from the specified directory to the target cluster.
Resources are applied in the correct dependency order:
1. Namespace
2. ConfigMap/Secret
3. Deployment
4. Service
5. Ingress

Template Repository (Optional):
  The --template-repo flag is optional. If provided, it will be used to:
  - Load component installType (kubectl/helm/custom) from config.yaml
  - Resolve component dependencies for correct ordering
  
  If not provided, the command will:
  - Use default kubectl apply for all components
  - Apply components in directory order

Examples:
  # Apply all kubernetes resources (without template repo, uses kubectl)
  blcli apply kubernetes -d ./generated/kubernetes

  # Apply with template repo (for installType and dependency resolution)
  blcli apply kubernetes -d ./generated/kubernetes --template-repo ./bl-template

  # Apply with specific context
  blcli apply kubernetes -d ./generated/kubernetes --context my-cluster

  # Dry-run mode
  blcli apply kubernetes -d ./generated/kubernetes --dry-run`,
		Example: `  # Apply all kubernetes resources (without template repo)
  blcli apply kubernetes -d ./generated/kubernetes

  # Apply with template repo (for installType and dependencies)
  blcli apply kubernetes -d ./generated/kubernetes --template-repo ./bl-template

  # Apply with specific context
  blcli apply kubernetes -d ./generated/kubernetes --context my-cluster

  # Dry-run mode
  blcli apply kubernetes -d ./generated/kubernetes --dry-run`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if applyKubernetesDir == "" {
				return fmt.Errorf("kubernetes directory is required. Use -d to specify the directory")
			}

			// Parse timeout
			timeout := 30 * time.Minute
			if applyKubernetesTimeout != "" {
				var err error
				timeout, err = time.ParseDuration(applyKubernetesTimeout)
				if err != nil {
					return fmt.Errorf("invalid timeout duration: %w", err)
				}
			}

			// Parse component wait (delay after each component before next)
			componentWait := 30 * time.Second
			if applyKubernetesComponentWait != "" && applyKubernetesComponentWait != "0" {
				var err error
				componentWait, err = time.ParseDuration(applyKubernetesComponentWait)
				if err != nil {
					return fmt.Errorf("invalid component-wait duration: %w", err)
				}
			} else if applyKubernetesComponentWait == "0" {
				componentWait = 0
			}

			// Don't print full usage on runtime errors (e.g. component apply failure)
			cmd.SilenceUsage = true

			// Create template loader if template repo is provided
			var templateLoader *template.Loader
			if templateRepo != "" {
				loaderOptions := template.LoaderOptions{
					ForceUpdate: forceUpdate,
					CacheExpiry: cacheExpiry,
				}
				if loaderOptions.CacheExpiry == 0 {
					loaderOptions.CacheExpiry = 24 * time.Hour
				}
				templateLoader = template.NewLoaderWithOptions(templateRepo, loaderOptions)
			}

			return bootstrap.ExecuteApplyKubernetes(bootstrap.ApplyKubernetesOptions{
				KubernetesDir:           applyKubernetesDir,
				ProjectName:             applyKubernetesProject,
				Kubeconfig:              applyKubernetesKubeconfig,
				Context:                 applyKubernetesContext,
				Namespace:               applyKubernetesNamespace,
				Timeout:                 timeout,
				DryRun:                  applyKubernetesDryRun,
				Wait:                    applyKubernetesWait,
				ComponentWaitAfterApply: componentWait,
			}, templateLoader)
		},
	}

	cmd.Flags().StringVarP(&applyKubernetesDir, "dir", "d", "",
		"Kubernetes directory path (required, generated by 'blcli init kubernetes')")
	cmd.Flags().StringVarP(&applyKubernetesProject, "project", "p", "",
		"Only apply components under this project (e.g. stg). If not set, applies all projects.")
	cmd.Flags().StringVar(&applyKubernetesKubeconfig, "kubeconfig", "",
		"kubeconfig file path (default: ~/.kube/config)")
	cmd.Flags().StringVar(&applyKubernetesContext, "context", "",
		"Kubernetes context name")
	cmd.Flags().StringVar(&applyKubernetesNamespace, "namespace", "",
		"Target namespace (if not specified, uses namespace from manifests)")
	cmd.Flags().StringVar(&applyKubernetesTimeout, "timeout", "30m",
		"Apply timeout duration (e.g., 30m, 1h). Default: 30m")
	cmd.Flags().BoolVar(&applyKubernetesDryRun, "dry-run", false,
		"Show what would be applied without actually applying")
	cmd.Flags().BoolVar(&applyKubernetesWait, "wait", true,
		"Wait for resources to be ready (default: true)")
	cmd.Flags().StringVar(&applyKubernetesComponentWait, "component-wait", "30s",
		"Wait duration after each component apply before next (e.g. 30s, 1m). Use 0 to disable. Default: 30s")
	cmd.Flags().StringVarP(&templateRepo, "template-repo", "r", "",
		"Template repository URL or local path (optional). If provided, loads installType and dependencies from config.yaml. If not provided, uses default kubectl apply for all components.")
	cmd.Flags().BoolVarP(&forceUpdate, "force-update", "f", false,
		"Force update templates from remote repository, ignoring cache")
	cmd.Flags().DurationVar(&cacheExpiry, "cache-expiry", 24*time.Hour,
		"Cache expiry duration for templates (e.g., 1h, 30m, 0 = no expiry)")

	return cmd
}
